bggRGjQaUbCoE/PiliPlus

lib/pages/live_room/controller.dart
lib/tcp/live.dart

1. replace tcp socket with wss socket to improve security
2. fallback live room danmu wss socket with all url until connected

two improves of live room danmu 

---

lib/models/video/play/url.dart
lib/utils/video_utils.dart

`backupUrl`里也出现了mcdn, 应在解析时就过滤掉它

skip mcdn on parsing

---

lib/common/widgets/list_sheet.dart
lib/common/widgets/spring_physics.dart
lib/pages/bangumi/view.dart
lib/pages/danmaku_block/index.dart
lib/pages/dynamics/view.dart
lib/pages/emote/view.dart
lib/pages/follow/view.dart
lib/pages/home/view.dart
lib/pages/member/new/member_page.dart
lib/pages/member_search/view.dart
lib/pages/search_result/view.dart
lib/pages/setting/widgets/model.dart
lib/pages/video/detail/view.dart
lib/utils/storage.dart

feat: custom spring #282

---

lib/grpc/grpc_repo.dart
lib/http/login.dart
lib/http/msg.dart
lib/utils/login.dart
lib/utils/utils.dart

2种randomString, 2种uuid, 2种buvid实现

remove duplicate code

---

lib/utils/utils.dart

revert genTraceId

---

lib/common/widgets/video_card_h.dart
lib/common/widgets/video_card_h_member_video.dart
lib/common/widgets/video_card_v.dart
lib/common/widgets/video_card_v_member_home.dart
lib/pages/bangumi/widgets/bangumi_card_v.dart
lib/pages/bangumi/widgets/bangumi_card_v_member_home.dart
lib/pages/dynamics/widgets/additional_panel.dart
lib/pages/dynamics/widgets/rich_node_panel.dart
lib/pages/fav_detail/controller.dart
lib/pages/fav_detail/widget/fav_video_card.dart
lib/pages/history/widgets/item.dart
lib/pages/later/controller.dart
lib/pages/member/new/content/member_contribute/content/video/member_video_ctr.dart
lib/pages/member_coin/widgets/item.dart
lib/pages/member_search/search_dynamic.dart
lib/pages/member_seasons/widgets/item.dart
lib/pages/setting/widgets/model.dart
lib/pages/subscription_detail/widget/sub_video_card.dart
lib/pages/video/detail/controller.dart
lib/pages/video/detail/introduction/controller.dart
lib/pages/video/detail/introduction/view.dart
lib/pages/video/detail/reply/controller.dart
lib/pages/video/detail/reply/view.dart
lib/pages/video/detail/view_v.dart
lib/pages/whisper_detail/widget/chat_item.dart
lib/router/app_pages.dart
lib/utils/app_scheme.dart
lib/utils/storage.dart
lib/utils/url_utils.dart
lib/utils/utils.dart

refa: vertical video page

---

lib/common/constants.dart
lib/http/api.dart
lib/http/init.dart
lib/http/interceptor.dart
lib/http/video.dart
lib/main.dart
lib/pages/setting/widgets/model.dart
lib/utils/storage.dart

- Brotil解压
- 连接复用(图片不走Dio所以还不能复用)
- HTTP/2支持(wip)

enable http2

---

lib/http/api.dart
lib/http/constants.dart
lib/http/msg.dart
lib/models/msg/msgfeed_sys_msg.dart
lib/pages/msg_feed_top/sys_msg/controller.dart
lib/utils/app_scheme.dart
lib/utils/utils.dart

- 用户信息伪装`android`端, 可以获得番剧的弹幕位置信息
- 系统信息改用`query_notify_list`, 这个api既有`msgSysUserNotify`, 也有`msgSysUnifiedNotify`的内容

update msg api

---

lib/common/widgets/report.dart
lib/pages/dynamics/widgets/author_panel.dart
lib/pages/video/detail/reply/widgets/reply_item.dart
lib/pages/video/detail/reply/widgets/reply_item_grpc.dart

report panel

---

lib/pages/video/detail/introduction/controller.dart
lib/pages/video/detail/introduction/view.dart
lib/pages/video/detail/view.dart
lib/pages/video/detail/view_v.dart

view later

---

lib/http/danmaku_block.dart
lib/models/user/danmaku_block.dart
lib/models/user/danmaku_rule.dart
lib/models/user/danmaku_rule_adapter.dart
lib/pages/danmaku/controller.dart
lib/pages/danmaku_block/index.dart
lib/pages/video/detail/widgets/header_control.dart
lib/plugin/pl_player/controller.dart
lib/utils/storage.dart

opt: danmaku filter

---

lib/http/init.dart
lib/http/retry_interceptor.dart
lib/main.dart
lib/pages/setting/widgets/model.dart
lib/pages/setting/widgets/slide_dialog.dart
lib/utils/storage.dart

feat: retry before sending

---

lib/pages/common/common_controller.dart
lib/pages/dynamics/controller.dart
lib/pages/home/controller.dart
lib/pages/main/view.dart
lib/pages/rank/controller.dart

feat: refresh on top

---

lib/pages/dynamics/widgets/author_panel.dart
lib/pages/dynamics/widgets/author_panel_grpc.dart
lib/pages/login/view.dart
lib/pages/setting/pages/play_speed_set.dart
lib/pages/video/detail/reply/widgets/reply_item.dart
lib/pages/video/detail/reply/widgets/reply_item_grpc.dart
lib/pages/video/detail/reply/widgets/reply_save.dart
lib/pages/video/detail/reply_reply/controller.dart
lib/utils/app_scheme.dart
lib/utils/download.dart
lib/utils/utils.dart
pubspec.lock
pubspec.yaml

feat: save reply

---

lib/common/widgets/avatar.dart
lib/pages/dynamics/widgets/author_panel.dart
lib/pages/dynamics/widgets/dynamic_panel.dart
lib/pages/member/widget/user_info_card.dart
lib/pages/search_panel/user/widgets/item.dart
lib/pages/video/detail/introduction/view.dart
lib/pages/video/detail/reply/widgets/reply_item_grpc.dart

refa: avatar (not radical)

---

lib/pages/article/widgets/opus_content.dart

feat: decoration color

---

lib/pages/main/controller.dart
lib/pages/main/view.dart
lib/pages/setting/models/style_settings.dart
lib/utils/storage_key.dart
lib/utils/storage_pref.dart

Add setting to control whether back button exits directly or returns to first tab

feat: add configurable main page back behavior

---

lib/pages/video/view.dart

修复IOS从后台恢复时全屏状态下屏幕方向错误的问题

---

lib/pages/common/multi_select/base.dart
lib/pages/fav/note/controller.dart
lib/pages/fav/pgc/controller.dart
lib/pages/fav_detail/controller.dart
lib/pages/history/controller.dart
lib/pages/history_search/controller.dart
lib/pages/later/controller.dart

`list.removeWhere(removeList.contains)`要求`removeList`必须为`Set`, 否则时间复杂度将为O(m*n), 甚至O(n^2)

revert: toSet

---

lib/common/widgets/interactiveviewer_gallery/interactiveviewer_gallery.dart
lib/common/widgets/marquee.dart
lib/http/api.dart
lib/http/music.dart
lib/models_new/music/bgm_detail.dart
lib/models_new/music/bgm_recommend_list.dart
lib/models_new/video/video_tag/data.dart
lib/pages/article/controller.dart
lib/pages/common/dyn/common_dyn_controller.dart
lib/pages/dynamics_detail/controller.dart
lib/pages/match_info/controller.dart
lib/pages/music/controller.dart
lib/pages/music/video/controller.dart
lib/pages/music/video/view.dart
lib/pages/music/view.dart
lib/pages/music/widget/music_video_card_h.dart
lib/pages/video/introduction/ugc/view.dart
lib/pages/video/widgets/header_control.dart
lib/router/app_pages.dart
lib/utils/app_scheme.dart
pubspec.lock
pubspec.yaml

1. 可查看bgm, 话题类tag可跳转
2. bgm页面
3. 在`RenderBox`层实现`Marquee`, 支持任意widget Marquee

feat: musicDetail

---

lib/models/common/audio_normalization.dart
lib/models/video/play/url.dart
lib/pages/setting/models/extra_settings.dart
lib/pages/setting/models/model.dart
lib/pages/setting/widgets/select_dialog.dart
lib/pages/setting/widgets/switch_item.dart
lib/pages/video/controller.dart
lib/pages/video/widgets/header_control.dart
lib/plugin/pl_player/controller.dart
lib/plugin/pl_player/widgets/mpv_convert_webp.dart
lib/utils/storage_key.dart
lib/utils/storage_pref.dart
pubspec.lock
pubspec.yaml

close #1349 在`lavfi-complex`中应用滤镜不会影响倍速
服务器提供了`loudnorm`所需的参数, 但`loudnorm`在较高倍速下仍可能产生音视频分离

feat: loudnorm
